apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: apperatorvaults.apperator.otaviof.github.io
spec:
  group: apperator.otaviof.github.io
  names:
    kind: ApperatorVault
    listKind: ApperatorVaultList
    plural: apperatorvaults
    singular: apperatorvault
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
