---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apperatorapp-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apperator
  template:
    metadata:
      labels:
        name: apperator
    spec:
      serviceAccountName: apperator
      containers:
        - name: apperator
          image: otaviof/apperator:latest
          command:
            - apperator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apperator"
          resources:
            requests:
              cpu: 100m
              memory: 128m
            limits:
              cpu: 300m
              memory: 512m
