apiVersion: apps/v1
kind: Deployment
metadata:
  name: apperator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apperator
  template:
    metadata:
      labels:
        name: apperator
    spec:
      serviceAccountName: apperator
      containers:
        - name: apperator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - apperator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apperator"
