apiVersion: v1
kind: Pod
metadata:
  name: apperator-test
spec:
  restartPolicy: Never
  containers:
  - name: apperator-test
    image: otaviof/apperator:latest
    imagePullPolicy: Always
    command: ["/go-test.sh"]
    env:
      - name: TEST_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
