// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorApp) DeepCopyInto(out *ApperatorApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorApp.
func (in *ApperatorApp) DeepCopy() *ApperatorApp {
	if in == nil {
		return nil
	}
	out := new(ApperatorApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApperatorApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorAppList) DeepCopyInto(out *ApperatorAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApperatorApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorAppList.
func (in *ApperatorAppList) DeepCopy() *ApperatorAppList {
	if in == nil {
		return nil
	}
	out := new(ApperatorAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApperatorAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorAppSpec) DeepCopyInto(out *ApperatorAppSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Sidecars != nil {
		in, out := &in.Sidecars, &out.Sidecars
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Probes != nil {
		in, out := &in.Probes, &out.Probes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorAppSpec.
func (in *ApperatorAppSpec) DeepCopy() *ApperatorAppSpec {
	if in == nil {
		return nil
	}
	out := new(ApperatorAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorAppStatus) DeepCopyInto(out *ApperatorAppStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorAppStatus.
func (in *ApperatorAppStatus) DeepCopy() *ApperatorAppStatus {
	if in == nil {
		return nil
	}
	out := new(ApperatorAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorContainer) DeepCopyInto(out *ApperatorContainer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorContainer.
func (in *ApperatorContainer) DeepCopy() *ApperatorContainer {
	if in == nil {
		return nil
	}
	out := new(ApperatorContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApperatorContainer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorContainerList) DeepCopyInto(out *ApperatorContainerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApperatorContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorContainerList.
func (in *ApperatorContainerList) DeepCopy() *ApperatorContainerList {
	if in == nil {
		return nil
	}
	out := new(ApperatorContainerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApperatorContainerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorContainerSpec) DeepCopyInto(out *ApperatorContainerSpec) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorContainerSpec.
func (in *ApperatorContainerSpec) DeepCopy() *ApperatorContainerSpec {
	if in == nil {
		return nil
	}
	out := new(ApperatorContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorContainerStatus) DeepCopyInto(out *ApperatorContainerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorContainerStatus.
func (in *ApperatorContainerStatus) DeepCopy() *ApperatorContainerStatus {
	if in == nil {
		return nil
	}
	out := new(ApperatorContainerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorEnv) DeepCopyInto(out *ApperatorEnv) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorEnv.
func (in *ApperatorEnv) DeepCopy() *ApperatorEnv {
	if in == nil {
		return nil
	}
	out := new(ApperatorEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApperatorEnv) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorEnvList) DeepCopyInto(out *ApperatorEnvList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApperatorEnv, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorEnvList.
func (in *ApperatorEnvList) DeepCopy() *ApperatorEnvList {
	if in == nil {
		return nil
	}
	out := new(ApperatorEnvList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApperatorEnvList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorEnvSpec) DeepCopyInto(out *ApperatorEnvSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorEnvSpec.
func (in *ApperatorEnvSpec) DeepCopy() *ApperatorEnvSpec {
	if in == nil {
		return nil
	}
	out := new(ApperatorEnvSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorEnvStatus) DeepCopyInto(out *ApperatorEnvStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorEnvStatus.
func (in *ApperatorEnvStatus) DeepCopy() *ApperatorEnvStatus {
	if in == nil {
		return nil
	}
	out := new(ApperatorEnvStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorProbe) DeepCopyInto(out *ApperatorProbe) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorProbe.
func (in *ApperatorProbe) DeepCopy() *ApperatorProbe {
	if in == nil {
		return nil
	}
	out := new(ApperatorProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApperatorProbe) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorProbeList) DeepCopyInto(out *ApperatorProbeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApperatorProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorProbeList.
func (in *ApperatorProbeList) DeepCopy() *ApperatorProbeList {
	if in == nil {
		return nil
	}
	out := new(ApperatorProbeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApperatorProbeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorProbeSpec) DeepCopyInto(out *ApperatorProbeSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorProbeSpec.
func (in *ApperatorProbeSpec) DeepCopy() *ApperatorProbeSpec {
	if in == nil {
		return nil
	}
	out := new(ApperatorProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorProbeStatus) DeepCopyInto(out *ApperatorProbeStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorProbeStatus.
func (in *ApperatorProbeStatus) DeepCopy() *ApperatorProbeStatus {
	if in == nil {
		return nil
	}
	out := new(ApperatorProbeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorVault) DeepCopyInto(out *ApperatorVault) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorVault.
func (in *ApperatorVault) DeepCopy() *ApperatorVault {
	if in == nil {
		return nil
	}
	out := new(ApperatorVault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApperatorVault) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorVaultList) DeepCopyInto(out *ApperatorVaultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApperatorVault, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorVaultList.
func (in *ApperatorVaultList) DeepCopy() *ApperatorVaultList {
	if in == nil {
		return nil
	}
	out := new(ApperatorVaultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApperatorVaultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorVaultSpec) DeepCopyInto(out *ApperatorVaultSpec) {
	*out = *in
	out.Authorization = in.Authorization
	in.Secrets.DeepCopyInto(&out.Secrets)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorVaultSpec.
func (in *ApperatorVaultSpec) DeepCopy() *ApperatorVaultSpec {
	if in == nil {
		return nil
	}
	out := new(ApperatorVaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApperatorVaultStatus) DeepCopyInto(out *ApperatorVaultStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApperatorVaultStatus.
func (in *ApperatorVaultStatus) DeepCopy() *ApperatorVaultStatus {
	if in == nil {
		return nil
	}
	out := new(ApperatorVaultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentSpec) DeepCopyInto(out *DeploymentSpec) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentSpec.
func (in *DeploymentSpec) DeepCopy() *DeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAuthorizationSecretKeysSpec) DeepCopyInto(out *VaultAuthorizationSecretKeysSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAuthorizationSecretKeysSpec.
func (in *VaultAuthorizationSecretKeysSpec) DeepCopy() *VaultAuthorizationSecretKeysSpec {
	if in == nil {
		return nil
	}
	out := new(VaultAuthorizationSecretKeysSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAuthorizationSpec) DeepCopyInto(out *VaultAuthorizationSpec) {
	*out = *in
	out.SecretKeys = in.SecretKeys
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAuthorizationSpec.
func (in *VaultAuthorizationSpec) DeepCopy() *VaultAuthorizationSpec {
	if in == nil {
		return nil
	}
	out := new(VaultAuthorizationSpec)
	in.DeepCopyInto(out)
	return out
}
